"""
Creates a dictionary with the same keys as the provided dictionary and
values generated by running the provided function for each value.
"""


def map_values(obj: dict, fn):
    # return {key: fn(val) for key, val in obj.items()}
    return dict((key, fn(val)) for key, val in obj.items())


nums = {
    '1': 1,
    '2': 2,
    '3': 3,
}
res = map_values(nums, lambda n: n * n)
print(res)

users = {
    'fred': {'user': 'fred', 'age': 40},
    'pebbles': {'user': 'pebbles', 'age': 1}
}
res = map_values(users, lambda u: u['age'])
print(res)
# {'fred': 40, 'pebbles': 1}
